clone:
  git:
    image: plugins/git
    tags: true

pipeline:
  test1:
    image: mhart/alpine-node:9.1.0
    group: testing
    secrets: [ test46 ]
    commands:
      - echo "node.js"
      - echo $TEST46

  test2:
    image: appleboy/golang-testing
    group: testing
    secrets: [ test46 ]
    commands:
      - echo "golang"
      - echo $TEST46
